apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    co.elastic.description: some description
    co.elastic.group: some group
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        co.elastic.description: some description
        co.elastic.group: some group
      creationTimestamp: null
      labels:
        io.kompose.network/magellan-front: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - image: rhodesjason/magellan-frontend
          name: frontend
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
